### ISSUE TITLE
ModuleNotFoundError: No module named 'base'

### ISSUE THREAD

**Issue by khouakhi** [moflaher/ttide_py#11]
I get this error when I import ttide after updating ttide

import ttide as tt
Traceback (most recent call last):

  File "<ipython-input-30-3549967828c9>", line 1, in <module>
    import ttide as tt

  File "C:\Users\AK\Anaconda3\lib\site-packages\ttide-0.3_exp-py3.6.egg\ttide\__init__.py", line 14, in <module>
    from base import TTideCon

ModuleNotFoundError: No module named 'base'

**Comment by feiger1992** [comment]
I had meet the same problem 
you should edit the __init__.py like this:
from ttide.base import TTideCon
and you will have the another ModuleNotFoundError like that ,edit the others
all of that is like the format " from *** import *** "
I don't know why neither,maybe the version of python?

**Comment by Harneet001** [comment]
(harneet) C:\python37\dev\harneet\src>python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\python37\dev\harneet\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\python37\dev\harneet\lib\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "C:\python37\dev\harneet\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\python37\dev\harneet\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\python37\dev\harneet\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\python37\dev\harneet\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\python37\dev\harneet\src\harneet\__init__.py", line 1, in <module>
    from .base import *
ModuleNotFoundError: No module named 'harneet.base'


please solve

**Comment by moflaher** [comment]
This should be resolved. Thanks for the fix.
